### PR TITLE
feat: torch examples on cpu

### PR DESCRIPTION
**Pull request by ThibaultFy**

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
Thanks!

**Review by oleobal — APPROVED** [review]
nice

**Pull request merged**
