### PR TITLE
feat: show version number

### PR DESCRIPTION
**Pull request by ThibaultFy**
Objective : show the version number in a clear manner for the user

### CODE REVIEW

**Comment by RomainGoussault** [comment]
What about removing the stable everywhere and putting the version number instead?

**Comment by ThibaultFy** [comment]
> What about removing the stable everywhere and putting the version number instead?

This is not possible, this is forced by ReadTheDoc. And the stable is still convenient to point url link always to the last version.
This PR is just a suggestion of method with which we can put the version number anywhere in the text

**Comment by oleobal** [comment]
So are we merging this? ^^

**Comment by ThibaultFy** [comment]
> So are we merging this? ^^

Don't know, it was more of a suggestion... I might close it in the end

**Comment by ThibaultFy** [comment]
Closing for non activity on the subject

**Pull request closed without merging**
