### PR TITLE
fix: pin substra-tools version in examples

### PR DESCRIPTION
**Pull request by ThibaultFy**
To change on next release, but to fix the CI in the meantime

### CODE REVIEW

**Comment by guilhem-barthes** [comment]
Is it the fix for the GPU?

**Comment by ThibaultFy** [comment]
> Is it the fix for the GPU?

No, it's suppose to fix the CI (doc examples)

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
> /e2e --tests=doc
> 
> > > Is it the fix for the GPU?
> > 
> > 
> > No, it's suppose to fix the CI (doc examples)
> 
> Should we run `/e2e`?

yep you're right

**Comment by ThibaultFy** [comment]
@thbcmlowk it passed

**Review by thbcmlowk — APPROVED** [review]

**Pull request merged**
